create database amazon_db;
use amazon_db;

/*  
1.Query the top 10 products by total sales value, including product name,total quantity sold, and total sales value.
*/
SELECT
    p.product_name,
    SUM(oi.quantity) AS total_quantity_sold,
    ROUND(SUM(oi.quantity * oi.price_per_unit), 2) AS total_sales_value
FROM order_items oi
JOIN products p 
    ON oi.product_id = p.product_id
JOIN category c
    ON p.category_id = c.category_id
GROUP BY p.product_id, p.product_name, c.category_name
ORDER BY total_sales_value DESC
LIMIT 10;
select * from customers;

-- 2.Calculate total revenue generated by each product category and include the percentage contribution of each category to total revenue.
SELECT
    c.category_name,
    ROUND(SUM(oi.quantity * oi.price_per_unit), 2) AS total_revenue,
    ROUND(
        SUM(oi.quantity * oi.price_per_unit) * 100.0 /
        SUM(SUM(oi.quantity * oi.price_per_unit)) OVER (),
        2
    ) AS revenue_percentage
FROM order_items oi
JOIN products p
    ON oi.product_id = p.product_id
JOIN category c
    ON p.category_id = c.category_id
GROUP BY c.category_name
ORDER BY total_revenue DESC;

-- 3.Compute the average order value (AOV) for each customer and include only customers with more than 5 orders.
WITH order_total AS (
    SELECT
        o.order_id,
        o.customer_id,
        SUM(oi.quantity * oi.price_per_unit) AS order_value
    FROM orders o
    JOIN order_items oi
        ON o.order_id = oi.order_id
    GROUP BY o.order_id, o.customer_id
)
SELECT
    customer_id,
    COUNT(order_id) AS total_orders,
    ROUND(AVG(order_value), 2) AS average_order_value
FROM order_total
GROUP BY customer_id
HAVING COUNT(order_id) > 5
ORDER BY average_order_value DESC;

-- 4.Query monthly total sales over the past year and display the current month’s sales along with the previous month’s sales.
WITH monthly_sales AS (
    SELECT
        DATE_FORMAT(o.order_date, '%Y-%m') AS sales_month,
        ROUND(SUM(oi.quantity * oi.price_per_unit), 2) AS total_sales
    FROM orders o
    JOIN order_items oi
        ON o.order_id = oi.order_id
    GROUP BY DATE_FORMAT(o.order_date, '%Y-%m')
)

SELECT
    sales_month,
    total_sales AS current_month_sales,
    LAG(total_sales) OVER (ORDER BY sales_month) AS previous_month_sales
FROM monthly_sales
ORDER BY sales_month;

-- 5. Find customers who have registered but never placed an order

SELECT
    customer_id,
    first_name,
    last_name,
    state from customers
where customer_id not in (select customer_id from orders);


--  6.Identify the least-selling product category for each state and include the  total sales for that category within each state. 

WITH category_sales AS (
SELECT  c.state,
		cat.category_name,
        ROUND(SUM(oi.quantity * oi.price_per_unit), 2) AS total_sales
FROM customers c
JOIN orders o
ON c.customer_id = o.customer_id
JOIN order_items oi
ON o.order_id = oi.order_id
JOIN products p
ON oi.product_id = p.product_id
JOIN category cat
ON p.category_id = cat.category_id
GROUP BY c.state, cat.category_name),
ranked_sales AS (
SELECT *,
		RANK() OVER (
			PARTITION BY state
			ORDER BY total_sales ASC
		) AS rnk
FROM category_sales)
SELECT
    state,
    category_name as least_selling_category,
    total_sales
FROM ranked_sales
WHERE rnk = 1
ORDER BY state
;

-- 7.Calculate the customer lifetime value (CLTV) for each customer and rank customers based on their CLTV.
SELECT c.customer_id,
	   concat(c.first_name ,' ', c.last_name) as customer_name,
	   round(sum(oi.price_per_unit * oi.quantity),2) as customer_lifetime_value,
       dense_rank() over( order by sum(oi.price_per_unit * oi.quantity)desc) as rank_customers
from order_items oi
join orders o
on oi.order_id=o.order_id
join customers c
on o.customer_id=c.customer_id
group by c.customer_id, customer_name
order by rank_customers 
;


-- 8.Query products with stock levels below a certain threshold (e.g., less than 10 units) and include the last restock date and warehouse information.
select
    p.product_name,
    i.stock as stock_quantity,
    i.last_stock_date,
    i.warehouse_id
from inventory i
join products p
    on i.product_id = p.product_id
where i.stock < 10
order by i.stock ;

-- 9.Calculate the percentage of successful payments across all orders and include a breakdown by payment status such as failed and pending.
select
    payment_status,
    count(*) as total_payments,
    round(
        count(*) * 100.0 / sum(count(*)) over (),
        2
    ) as percentage
from payments
group by payment_status
order by total_payments desc;


-- 10.Query the top 10 products by the number of returns and display the return rate as a percentage of total units sold for each product.
-- Overall return rate by orders
WITH product_returns AS (
    SELECT
        p.product_id,
        p.product_name,
        SUM(oi.quantity) AS total_units_sold,

        SUM(
            CASE
                WHEN TRIM(s.delivery_status) = 'Returned'
                THEN oi.quantity
                ELSE 0
            END
        ) AS returned_units

    FROM products p
    JOIN order_items oi
        ON p.product_id = oi.product_id
    JOIN shipping s
        ON oi.order_id = s.order_id

    GROUP BY
        p.product_id,
        p.product_name
)

SELECT
    product_name,
    total_units_sold,
    returned_units,
    ROUND(
        returned_units * 100.0 / total_units_sold,
        2
    ) AS return_rate_percentage
FROM product_returns
WHERE returned_units > 0
ORDER BY returned_units DESC, return_rate_percentage DESC
limit 10;

-- 11.Month-over-Month (MoM) Growth
with monthly_sales as(
select 
DATE_FORMAT(o.order_date, '%M %Y') AS month ,
round(sum(oi.price_per_unit * oi.quantity),2) as revenue,
DATE_FORMAT(o.order_date, '%Y-%m') AS month_key
from orders o
join order_items oi
on o.order_id=oi.order_id
group by month_key,month
),
growth AS (
    SELECT
        month_key,
        month,
        revenue,
        LAG(revenue) OVER(ORDER BY month_key) AS previous_month
    FROM monthly_sales
)
select 
	month,
	revenue,previous_month, 
	 COALESCE(
     ROUND(((revenue - previous_month) / previous_month) * 100, 2),
     0) as growth_percent 
from growth
order by month_key;

-- 12.Customer Segmentation
with segments as(
select 
	round(sum(oi.price_per_unit * oi.quantity),2) as customer_lifetime_value,
	c.customer_id 
from order_items oi
join orders o
on oi.order_id=o.order_id
join customers c
on o.customer_id=c.customer_id
group by c.customer_id 
),
customer_segmentation as (select customer_id , customer_lifetime_value,
    Case 
		when customer_lifetime_value>50000 then 'Platinium'
        when customer_lifetime_value between 20000 and 50000 then 'Gold'
        when customer_lifetime_value between 10000 and 20000 then 'Silver'
        else 'Bronze'
	end as segment
        
from segments
ORDER BY customer_lifetime_value DESC),
customer_percent as(
select 
    segment,
    COUNT(*) AS total_customers
from customer_segmentation
GROUP BY segment)
select
	segment,total_customers,
    ROUND(
     total_customers* 100.0 /
    SUM(total_customers) over(),
    2
) AS customer_percentage
from customer_percent
order by total_customers desc
;

-- 13.Inventory Risk Matrix
with inventory_analysis  as (
select p.product_name as product_name , i.stock as stock , sum(oi.quantity) as unit_sold
from inventory i
join products p 
on i.product_id=p.product_id
join order_items oi
on p.product_id=oi.product_id
group by p.product_name,i.stock
),
inventory_status as
(select product_name, stock,unit_Sold,
case 
	when unit_sold >= 120 and stock <= 40 then 'Restock immediately'
    when unit_sold <= 70 and stock>=80 then 'overstock'
    when unit_sold >=120 and stock>=40  then 'Healthy'
    else 'Normal'
end as inventory_status
from inventory_analysis) 
select
    inventory_status,
    count(*) as total_products
from inventory_status
group by inventory_status
order by total_products desc;

-- 14.Pareto (80/20) Analysis
WITH product_revenue AS (
    SELECT
        p.product_id,
        p.product_name,
        ROUND(SUM(oi.quantity * oi.price_per_unit),2) AS revenue
    FROM products p
    JOIN order_items oi
        ON p.product_id = oi.product_id
    GROUP BY
        p.product_id,
        p.product_name
),

pareto AS (
    SELECT
        product_id,
        product_name,
        revenue,
        round(SUM(revenue) OVER (
            ORDER BY revenue DESC
        ),2) AS cumulative_revenue,
        SUM(revenue) OVER () AS total_revenue
    FROM product_revenue
)
SELECT
    product_name,
    revenue,
    cumulative_revenue,
    ROUND(
        (cumulative_revenue / total_revenue) * 100,
        2
    ) AS cumulative_percentage,
    CASE
        WHEN (cumulative_revenue / total_revenue) <= 0.80
        THEN 'Top 80% Revenue'
        ELSE 'Remaining 20%'
    END AS pareto_category
FROM pareto
ORDER BY revenue DESC;

-- 15.ABC Product Classification
WITH product_revenue AS (
    SELECT
        p.product_id,
        p.product_name,
        SUM(oi.quantity * oi.price_per_unit) AS revenue
    FROM products p
    JOIN order_items oi
        ON p.product_id = oi.product_id
    GROUP BY p.product_id, p.product_name
),
abc_analysis AS (
    SELECT
        product_name,
        revenue,
        CASE
            WHEN SUM(revenue) OVER (ORDER BY revenue DESC)
                 / SUM(revenue) OVER () <= 0.80 THEN 'A'
            WHEN SUM(revenue) OVER (ORDER BY revenue DESC)
                 / SUM(revenue) OVER () <= 0.95 THEN 'B'
            ELSE 'C'
        END AS abc_category
    FROM product_revenue
)

SELECT
    abc_category,
    COUNT(*) AS total_products,
    ROUND(SUM(revenue),2) AS category_revenue
FROM abc_analysis
GROUP BY abc_category
ORDER BY abc_category;

